// Generated by VpuParams during Chipyard elaboration. Do not edit.
// This single header describes the most recently elaborated VPU configuration.
#ifndef GEMMINI_ROCC_TESTS_INCLUDE_VPU_PARAMS_H_
#define GEMMINI_ROCC_TESTS_INCLUDE_VPU_PARAMS_H_

#define VPU_HAS_GENERATED_PARAMS 1

#ifndef VPU_STORAGE_FP32
#define VPU_STORAGE_FP32 0
#endif
#ifndef VPU_STORAGE_BF16
#define VPU_STORAGE_BF16 1
#endif

#define VPU_VLEN 128u
#define VPU_NLANES 16u
#define VPU_VMASK_CHUNKS 2u
#define VPU_VMASK_CHUNK_BITS 64u
#define VPU_MASK_SLOTS 4u
#define VPU_GATHER_INDEX_BITS 7u
#define VPU_SFU_LANES 4u
#define VPU_RECIPROCAL_LANES 4u
#define VPU_RECIPROCAL_FMAS_PER_LANE 4u
#define VPU_RECIPROCAL_LATENCY 13u
#define VPU_VSPAD_KIB 256u
#define VPU_VSPAD_BANKS 8u
#define VPU_VSPAD_SUBBANKS 4u
#define VPU_MATRIX_PORTS 1u
#define VPU_MATRIX_ROW_ELEMENTS 32u
#define VPU_MATRIX_WORDS_PER_ROW 2u
#define VPU_SHARED_DEPS 1u
#define VPU_DMA_MAX_ROWS 64u
#define VPU_STORAGE_KIND VPU_STORAGE_FP32
#define VPU_COMPUTE_KIND VPU_STORAGE_FP32
#define VPU_DMA_BUS_BITS 256u
#define VPU_DMA_MAX_BYTES 64u
#define VPU_DMA_MAX_IN_FLIGHT 8u
#define VPU_DMA_READ_MERGE_ENTRIES 18u
#define VPU_LOAD_QUEUE_ENTRIES 4u
#define VPU_EXEC_QUEUE_ENTRIES 8u
#define VPU_STORE_QUEUE_ENTRIES 4u
#define VPU_LOAD_RS_ENTRIES 4u
#define VPU_EXEC_RS_ENTRIES 9u
#define VPU_STORE_RS_ENTRIES 4u
#define VPU_HAZARD_ENTRIES 17u
#define VPU_RS_TAG_BITS 5u
#define VPU_DMA_COMMAND_TAG_BITS 2u
#define VPU_TLB_ENTRIES 4u
#define VPU_EXP_TABLE_ENTRIES 64u
#define VPU_RECIPROCAL_REFINE_ITERS 2u
#define VPU_FMA_PIPE_DEPTH 4u
#define VPU_FP_STATE_ENTRIES 256u
#define VPU_FP_STATE_BANKS 4u
#define VPU_LOOP_BUFFER_ENTRIES 64u
#define VPU_LOOP_STACK_DEPTH 4u
#define VPU_GROUP_ID_BITS 3u
#define VPU_GROUP_ID_SHIFT 32u
#define VPU_GROUPED_SHIFT 35u
#define VPU_GROUP_LAST_SHIFT 36u
#define VPU_GROUPED_COMMANDS 1u

#if VPU_STORAGE_KIND == VPU_STORAGE_FP32
#define VPU_STORAGE_BITS 32u
#elif VPU_STORAGE_KIND == VPU_STORAGE_BF16
#define VPU_STORAGE_BITS 16u
#else
#error "VPU_STORAGE_KIND must be VPU_STORAGE_FP32 or VPU_STORAGE_BF16"
#endif

#define VPU_STORAGE_BYTES (VPU_STORAGE_BITS / 8u)
#define VPU_VSPAD_BYTES (VPU_VSPAD_KIB * 1024u)
#define VPU_VSPAD_ELEMENTS (VPU_VSPAD_BYTES / VPU_STORAGE_BYTES)
#define VPU_ELEMENTS_PER_BANK (VPU_VSPAD_ELEMENTS / VPU_VSPAD_BANKS)
#define VPU_VECTOR_BYTES (VPU_VLEN * VPU_STORAGE_BYTES)
#define VPU_SLOTS_PER_BANK (VPU_ELEMENTS_PER_BANK / VPU_VLEN)

/* VSRAM addresses are element addresses, not byte addresses. */
#define VPU_BANK_BASE(bank_) ((unsigned)(bank_) * VPU_ELEMENTS_PER_BANK)
#define VPU_SLOT_ADDR(bank_, slot_)                                      \
  (VPU_BANK_BASE(bank_) + (unsigned)(slot_) * VPU_VLEN)

/* Recommended software-managed double-buffer layout. */
#define VPU_PING_INPUT_ADDR VPU_BANK_BASE(0u)
#define VPU_PING_TEMP0_ADDR VPU_BANK_BASE(1u)
#define VPU_PING_TEMP1_ADDR VPU_BANK_BASE(2u)
#define VPU_PING_OUTPUT_ADDR VPU_BANK_BASE(3u)
#define VPU_PONG_INPUT_ADDR VPU_BANK_BASE(4u)
#define VPU_PONG_TEMP0_ADDR VPU_BANK_BASE(5u)
#define VPU_PONG_TEMP1_ADDR VPU_BANK_BASE(6u)
#define VPU_PONG_OUTPUT_ADDR VPU_BANK_BASE(7u)

#if VPU_COMPUTE_KIND != VPU_STORAGE_FP32
#error "VPU v1 compute type must be FP32"
#endif

#if (VPU_VLEN == 0) || ((VPU_VLEN % VPU_NLANES) != 0)
#error "VPU_VLEN must be a non-zero multiple of VPU_NLANES"
#endif

#if (VPU_SFU_LANES == 0) || ((VPU_NLANES % VPU_SFU_LANES) != 0)
#error "VPU_SFU_LANES must be a non-zero divisor of VPU_NLANES"
#endif

#if (VPU_RECIPROCAL_LANES == 0) || \
    ((VPU_NLANES % VPU_RECIPROCAL_LANES) != 0) || \
    ((VPU_RECIPROCAL_LANES * VPU_RECIPROCAL_FMAS_PER_LANE) != VPU_NLANES)
#error "VPU reciprocal lanes must exactly partition the shared FMA lanes"
#endif

#if (VPU_VSPAD_BANKS == 0) || \
    ((VPU_VSPAD_BANKS & (VPU_VSPAD_BANKS - 1)) != 0)
#error "VPU_VSPAD_BANKS must be a power of two"
#endif

#if (VPU_VSPAD_SUBBANKS == 0) || \
    ((VPU_VSPAD_SUBBANKS & (VPU_VSPAD_SUBBANKS - 1)) != 0)
#error "VPU_VSPAD_SUBBANKS must be a power of two"
#endif

#if ((VPU_VSPAD_BYTES % VPU_VSPAD_BANKS) != 0) || \
    ((VPU_VSPAD_BYTES % VPU_STORAGE_BYTES) != 0)
#error "VPU scratchpad size must divide evenly into banks and elements"
#endif

#if (VPU_ELEMENTS_PER_BANK < VPU_VLEN) || \
    ((VPU_ELEMENTS_PER_BANK % VPU_VLEN) != 0)
#error "Each VPU bank must contain an integral number of architectural vectors"
#endif

#if VPU_SLOTS_PER_BANK == 0
#error "Each VPU bank must expose at least one architectural vector slot"
#endif

#if (VPU_SLOTS_PER_BANK * VPU_VLEN) != VPU_ELEMENTS_PER_BANK
#error "VPU slot geometry must cover each bank exactly"
#endif

#if VPU_VSPAD_BANKS < 8
#error "The public ping/pong VSRAM layout requires at least eight banks"
#endif

#if VPU_FMA_PIPE_DEPTH != 4
#error "The VPU v1 software ABI requires VPU_FMA_PIPE_DEPTH=4"
#endif

#if VPU_SHARED_DEPS && !VPU_GROUPED_COMMANDS
#error "Shared Gemmini/VPU dependencies require grouped commands"
#endif

#if VPU_MATRIX_PORTS && VPU_STORAGE_KIND != VPU_STORAGE_FP32
#error "The v1 Gemmini matrix bridge requires FP32 VPU storage"
#endif

#endif  // GEMMINI_ROCC_TESTS_INCLUDE_VPU_PARAMS_H_
